# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      
      - add_ssh_keys:
          fingerprints:
            - "33:9a:cf:aa:8c:9a:7d:3d:62:43:47:47:7f:09:7b:14"

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
     
     # Install SL agent!
      - run: 
          name: Install Shiftleft agent!
          command: curl https://www.shiftleft.io/download/sl-latest-linux-x64.tar.gz > /tmp/sl.tar.gz && sudo tar -C /usr/local/bin -xzf /tmp/sl.tar.gz

    # Install Ocular!
      - run: 
          name: Install Ocular Installation!
          command: sl update ocular
     
     # build the apps
      - run: 
          name: Build the application!
          command: mvn clean package

      # run tests!
      - run: mvn integration-test
      
      # Get analysis scripts!
      - run: 
          name: Get hardcoded literal Analysis scripts
          command: |
            cd /home/circleci/.shiftleft/ocular/
            git clone git@github.com:ShiftLeftSecurity/scripts-internal.git
      
      # Analyze for security!
      - run: 
          name: Analyze for hardcoded literals
          command: ./ocular.sh --script scripts-internal/java/sensitive/main.sc --params payloadType=WAR,payload=$CIRCLE_WORKING_DIRECTORY/target/servlettarpit.war,scriptType=SENSITIVE_LITERAL,nameSpace=".*(io.shiftleft).*",outFile=sensitive_literal.json
  
      # Print hardcoded literals!
      - run: 
          name: Analyze for hardcoded literals
          command: cat sensitive_literal.json
  
    
      
