name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      appName: ${{'TARPIT'}}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    # Install SL agent
    - name: Install Shiftleft agent!
      run: curl https://www.shiftleft.io/download/sl-latest-linux-x64.tar.gz > /tmp/sl.tar.gz && sudo tar -C /usr/local/bin -xzf /tmp/sl.tar.gz
    - name: Run code analysis
      run: sl analyze --wait --app $appName target/servlettarpit.war
